language: c
sudo: false # only for faster builds
script:
  - ./bootstrap.sh
  - ./configure --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-systemd=/usr/lib/systemd/system --disable-icatok --disable-ccatok --enable-testcases
  - make

after_success:
