# https://twindb.com/building-rpm-on-travis-ci-in-docker-containers/
# https://github.com/twindb/backup/blob/develop/.travis.yml
sudo: required

env:
  matrix:
    - PLATFORM=centos DISTRO=el OS_VERSION=7 DOCKER_IMAGE=centos:centos7

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo docker pull ${DOCKER_IMAGE}

script:
  - make -f Makefile.CI docker-rpm
  - make -f Makefile.CI list

before_deploy:
  - travis_wait 30 make package

deploy:

notifications:
