.PHONY: docker-rpm list
.DEFAULT_GOAL := docker-rpm

list:
	@sudo docker run \
		centos:centos${OS_VERSION} ls -l ~/rpmbuild/RPMS

.PHONY: docker-rpm
docker-rpm: ## create virtual environment typically used for development purposes
	@sudo docker run \
		-v `pwd`:/opencryptoki-${OCK_VERSION}:rw centos:centos${OS_VERSION} \
		/bin/bash /opencryptoki-${OCK_VERSION}/support/bootstrap-docker.sh

